wordsByCategory:
  семья:
    - word: бабушка
      hint: Близкий старый родственник
    - word: дедушка
      hint: Близкий старый родственник
    - word: мама
      hint: Очень близкий родственник
    - word: папа
      hint: Очень близкий родственник
    - word: брат
      hint: Близкий родственник примерно ровесник
    - word: сестра
      hint: Близкий родственник примерно ровесник
  фрукты:
    - word: яблоко
      hint: Круглый фрукт
    - word: банан
      hint: Вытянутый фрукт
    - word: груша
      hint: Фрукт и фигура
    - word: слива
      hint: Фрукт и нос
    - word: лимон
      hint: Кислый фрукт
  животные:
    - word: кошка
      hint: Домашнее животное
    - word: собака
      hint: Домашнее животное
    - word: лиса
      hint: Дикое животное
    - word: волк
      hint: Дикое животное
    - word: медведь
      hint: Дикое животное
    - word: слон
      hint: Животное из теплых стран
    - word: жираф
      hint: Животное из теплых стран
    - word: тигр
      hint: Животное из теплых стран
    - word: лев
      hint: Животное из теплых стран
    - word: зебра
      hint: Животное из теплых стран
    - word: кенгуру
      hint: Животное из теплых стран
  города:
    - word: москва
      hint: Город в России
    - word: петербург
      hint: Город в России
    - word: париж
      hint: Город во Франции
    - word: лондон
      hint: Город в Англии
    - word: токیو
      hint: Город в Японии
    - word: ньюйорк
      hint: Город в США
    - word: берлин
      hint: Город в Германии
    - word: рим
      hint: Город в Италии
    - word: стамбул
      hint: Город в Турции
    - word: киев
      hint: Город в Украине
    - word: минск
      hint: Город в Беларуси

difficulties:
  EASY:
    maxMistakes: 8
    minWordLength: 3
    maxWordLength: 6
  MEDIUM:
    maxMistakes: 6
    minWordLength: 4
    maxWordLength: 8
  HARD:
    maxMistakes: 5
    minWordLength: 6
    maxWordLength: 20
